# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions
# CC 	= purify cc
include Target.include
include .applTop/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS	=

# User compiler and loader flags
USR_CFLAGS   = -g
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
# SRCS.c	= $(wildcard ../*.c) 
SRCS.c	= \
	../buffers.c  \
	../cfileio.c  \
	../checksum.c  \
	../compress.c  \
	../editcol.c  \
	../edithdu.c  \
	../fitscore.c  \
	../getcol.c  \
	../getcolb.c  \
	../getcold.c  \
	../getcole.c  \
	../getcoli.c  \
	../getcolj.c  \
	../getcolk.c  \
	../getcoll.c  \
	../getcols.c  \
	../getcolui.c  \
	../getcoluj.c  \
	../getkey.c  \
	../modkey.c  \
	../putcol.c  \
	../putcolb.c  \
	../putcold.c  \
	../putcole.c  \
	../putcoli.c  \
	../putcolj.c  \
	../putcolk.c  \
	../putcoll.c  \
	../putcols.c  \
	../putcolu.c  \
	../putcolui.c  \
	../putcoluj.c  \
	../putkey.c  \
	../scalnull.c  \
	../swapproc.c  \
	../wcsutil.c


# Add the object files in one of these two variables. 
# LIBOBJS += test.o
LIBOBJS =  $(strip $(patsubst ../%.c,	 %.o, $(SRCS.c)))
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
#PROD	= $(patsubst %.o, %, $(OBJS))
PROD	= $(OBJS)						     \
		  $(patsubst ../%.vws, %, $(wildcard ../*.vws))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	= cFitsIo

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	= $(wildcard ../resource.def)

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)

TARGETS =

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added or modified if required
#$(PROD): $(OBJS) $(DEPLIBS)
#	$(RM) $@
#	$(LINK.c) -o $@ $(OBJS) $(LDLIBS)



